FROM node:latest

# Create app directory
WORKDIR /usr/src/app

# Install server dependencies
COPY server/package*.json ./server/
RUN npm install --prefix server

# Copy server source
COPY server/ ./server/

# Install client dependencies
COPY client/package*.json ./client/
RUN npm install --prefix client

# Define environemnt/argument variables
ARG OPEN_AI_API_ACCESS_KEY
ENV OPEN_AI_API_ACCESS_KEY=${OPEN_AI_API_ACCESS_KEY}

ARG REACT_APP_FIREBASE_API_KEY
ENV REACT_APP_FIREBASE_API_KEY=${REACT_APP_FIREBASE_API_KEY}

ARG REACT_APP_FIREBASE_AUTH_DOMAIN
ENV REACT_APP_FIREBASE_AUTH_DOMAIN=${REACT_APP_FIREBASE_AUTH_DOMAIN}

ARG REACT_APP_FIREBASE_PROJECT_ID
ENV REACT_APP_FIREBASE_PROJECT_ID=${REACT_APP_FIREBASE_PROJECT_ID}

ARG REACT_APP_FIREBASE_STORAGE_BUCKET
ENV REACT_APP_FIREBASE_STORAGE_BUCKET=${REACT_APP_FIREBASE_STORAGE_BUCKET}

ARG REACT_APP_FIREBASE_MESSAGING_SENDER_ID
ENV REACT_APP_FIREBASE_MESSAGING_SENDER_ID=${REACT_APP_FIREBASE_MESSAGING_SENDER_ID}

ARG REACT_APP_FIREBASE_APP_ID
ENV REACT_APP_FIREBASE_APP_ID=${REACT_APP_FIREBASE_APP_ID}

ARG REACT_APP_FIREBASE_MEASUREMENT_ID
ENV REACT_APP_FIREBASE_MEASUREMENT_ID=${REACT_APP_FIREBASE_MEASUREMENT_ID}

# Build client
COPY client/ ./client/
RUN npm run build --prefix client

# Expose the port the app runs on
EXPOSE 3000

# Start server
ENTRYPOINT ["node", "./server/server.js"]