version: '0.1'
services:
  app:
    image: navdeep16/speachy:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - BUILD=production
      - LOG_LEVEL=debug

  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - app