FROM node:16.17

# Create app directory
WORKDIR /usr/src/app

# Install server dependencies
COPY server/package*.json ./server/
RUN npm install --prefix server

# Copy server source (including the firebase-admin-security.json file)
COPY server/ ./server/

# Install client dependencies
COPY client/package*.json ./client/
RUN npm install --prefix client

# Define environment/argument variables
ARG OPEN_AI_API_ACCESS_KEY
ENV OPEN_AI_API_ACCESS_KEY=${OPEN_AI_API_ACCESS_KEY}

ARG REACT_APP_ENV
ENV REACT_APP_ENV=${REACT_APP_ENV}

ARG REACT_APP_FIREBASE_API_KEY
ENV REACT_APP_FIREBASE_API_KEY=${REACT_APP_FIREBASE_API_KEY}

ARG REACT_APP_FIREBASE_AUTH_DOMAIN
ENV REACT_APP_FIREBASE_AUTH_DOMAIN=${REACT_APP_FIREBASE_AUTH_DOMAIN}

ARG REACT_APP_FIREBASE_PROJECT_ID
ENV REACT_APP_FIREBASE_PROJECT_ID=${REACT_APP_FIREBASE_PROJECT_ID}

ARG REACT_APP_FIREBASE_STORAGE_BUCKET
ENV REACT_APP_FIREBASE_STORAGE_BUCKET=${REACT_APP_FIREBASE_STORAGE_BUCKET}

ARG REACT_APP_FIREBASE_MESSAGING_SENDER_ID
ENV REACT_APP_FIREBASE_MESSAGING_SENDER_ID=${REACT_APP_FIREBASE_MESSAGING_SENDER_ID}

ARG REACT_APP_FIREBASE_APP_ID
ENV REACT_APP_FIREBASE_APP_ID=${REACT_APP_FIREBASE_APP_ID}

ARG REACT_APP_FIREBASE_MEASUREMENT_ID
ENV REACT_APP_FIREBASE_MEASUREMENT_ID=${REACT_APP_FIREBASE_MEASUREMENT_ID}

ARG FB_DEV_BASE64_ENCODED_SERVICE_ACCOUNT
ENV FB_DEV_BASE64_ENCODED_SERVICE_ACCOUNT=${FB_DEV_BASE64_ENCODED_SERVICE_ACCOUNT}

ARG NODE_DSN
ENV NODE_DSN=${NODE_DSN}

ARG REACT_DSN
ENV REACT_DSN=${REACT_DSN}

ARG SENTRY_AUTH_TOKEN
ENV SENTRY_AUTH_TOKEN=${SENTRY_AUTH_TOKEN}

# Load Stripe Environment Variables
ARG STRIPE_API_KEY
ENV STRIPE_API_KEY=${STRIPE_API_KEY}

ARG STRIPE_WEBHOOK_SECRET
ENV STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}

# Build client
COPY client/ ./client/
RUN npm run build --prefix client

# Expose the port the app runs on
EXPOSE 3000

# Start server
ENTRYPOINT ["node", "./server/server.js"]