name: Speachy Development CI

on:
  push:
    branches: ["development"]
  pull_request:
    branches: ["development"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Firebase Admin SDK
        run: echo ${{ secrets.FIREBASE_ADMIN_SDK }} | base64 --decode > ./server/firebase-admin-security.json

      - name: Debug secret variables and file existence
        run: |
          echo "DEV_OPEN_AI_API_ACCESS_KEY=${{ secrets.DEV_OPEN_AI_API_ACCESS_KEY }}"
          ls server
          cat server/firebase-admin-security.json

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: List server directory contents before Docker build
        run: ls -la ./server

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/speachy:test-ci
          no-cache: true
          build-args: |
            OPEN_AI_API_ACCESS_KEY=${{ secrets.DEV_OPEN_AI_API_ACCESS_KEY }}
            REACT_APP_FIREBASE_API_KEY=${{ secrets.DEV_REACT_APP_FIREBASE_API_KEY }}
            REACT_APP_FIREBASE_AUTH_DOMAIN=${{ secrets.DEV_REACT_APP_FIREBASE_AUTH_DOMAIN }}
            REACT_APP_FIREBASE_PROJECT_ID=${{ secrets.DEV_REACT_APP_FIREBASE_PROJECT_ID }}
            REACT_APP_FIREBASE_STORAGE_BUCKET=${{ secrets.DEV_REACT_APP_FIREBASE_STORAGE_BUCKET }}
            REACT_APP_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.DEV_REACT_APP_FIREBASE_MESSAGING_SENDER_ID }}
            REACT_APP_FIREBASE_APP_ID=${{ secrets.DEV_REACT_APP_FIREBASE_APP_ID }}
            REACT_APP_FIREBASE_MEASUREMENT_ID=${{ secrets.DEV_REACT_APP_FIREBASE_MEASUREMENT_ID }}
            FB_DEV_PROJECT_ID=${{ secrets.FB_DEV_PROJECT_ID }}
            FB_DEV_PRIVATE_KEY=${{ secrets.FB_DEV_PRIVATE_KEY }}
            FB_DEV_PRIVATE_KEY_ID=${{ secrets.FB_DEV_PRIVATE_KEY_ID }}
            FB_DEV_CLIENT_EMAIL=${{ secrets.FB_DEV_CLIENT_EMAIL }}
            FB_DEV_CLIENT_ID=${{ secrets.FB_DEV_CLIENT_ID }}
            FB_DEV_CLIENT_X509_CERT_URL=${{ secrets.FB_DEV_CLIENT_X509_CERT_URL }}
            NODE_DSN=${{ secrets.DEV_NODE_DSN }}
            REACT_DSN=${{ secrets.DEV_REACT_DSN }}
            SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}
            STRIPE_API_KEY=${{ secrets.DEV_STRIPE_API_KEY }}
            STRIPE_WEBHOOK_SECRET=${{ secrets.DEV_STRIPE_WEBHOOK_SECRET }}
